//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APAM.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class APAM_DBEntitiesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APAM_DBEntitiesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APAM.Localization.APAM_DBEntitiesResources", typeof(APAM_DBEntitiesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress Id.
        /// </summary>
        public static string Address_AdressId {
            get {
                return ResourceManager.GetString("Address_AdressId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment Number.
        /// </summary>
        public static string Address_ApartmentNumber {
            get {
                return ResourceManager.GetString("Address_ApartmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Letter.
        /// </summary>
        public static string Address_BuildingLetter {
            get {
                return ResourceManager.GetString("Address_BuildingLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Number.
        /// </summary>
        public static string Address_BuildingNumber {
            get {
                return ResourceManager.GetString("Address_BuildingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corpus Number.
        /// </summary>
        public static string Address_CorpusNumber {
            get {
                return ResourceManager.GetString("Address_CorpusNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string Address_District {
            get {
                return ResourceManager.GetString("Address_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Address_PostalCode {
            get {
                return ResourceManager.GetString("Address_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Address_Region {
            get {
                return ResourceManager.GetString("Address_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement.
        /// </summary>
        public static string Address_Settlement {
            get {
                return ResourceManager.GetString("Address_Settlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Address_Street {
            get {
                return ResourceManager.GetString("Address_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string AddressPlural {
            get {
                return ResourceManager.GetString("AddressPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Id.
        /// </summary>
        public static string Administrator_AdministratorId {
            get {
                return ResourceManager.GetString("Administrator_AdministratorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Type.
        /// </summary>
        public static string Administrator_AdministratorType {
            get {
                return ResourceManager.GetString("Administrator_AdministratorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string Administrator_MiddleName {
            get {
                return ResourceManager.GetString("Administrator_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Administrator_Name {
            get {
                return ResourceManager.GetString("Administrator_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Administrator_Surname {
            get {
                return ResourceManager.GetString("Administrator_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Contact.
        /// </summary>
        public static string AdministratorContact {
            get {
                return ResourceManager.GetString("AdministratorContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string AdministratorContact_Administrator {
            get {
                return ResourceManager.GetString("AdministratorContact_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Contact Id.
        /// </summary>
        public static string AdministratorContact_AdministratorContactId {
            get {
                return ResourceManager.GetString("AdministratorContact_AdministratorContactId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        public static string AdministratorContact_ContactType {
            get {
                return ResourceManager.GetString("AdministratorContact_ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string AdministratorContact_Value {
            get {
                return ResourceManager.GetString("AdministratorContact_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Contacts.
        /// </summary>
        public static string AdministratorContactPlural {
            get {
                return ResourceManager.GetString("AdministratorContactPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrators.
        /// </summary>
        public static string AdministratorPlural {
            get {
                return ResourceManager.GetString("AdministratorPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Salary.
        /// </summary>
        public static string AdministratorSalary {
            get {
                return ResourceManager.GetString("AdministratorSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string AdministratorSalary_Administrator {
            get {
                return ResourceManager.GetString("AdministratorSalary_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Salary Id.
        /// </summary>
        public static string AdministratorSalary_AdministratorSalaryId {
            get {
                return ResourceManager.GetString("AdministratorSalary_AdministratorSalaryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string AdministratorSalary_IssueDate {
            get {
                return ResourceManager.GetString("AdministratorSalary_IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string AdministratorSalary_Salary {
            get {
                return ResourceManager.GetString("AdministratorSalary_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Salaries.
        /// </summary>
        public static string AdministratorSalaryPlural {
            get {
                return ResourceManager.GetString("AdministratorSalaryPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Type.
        /// </summary>
        public static string AdministratorType {
            get {
                return ResourceManager.GetString("AdministratorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Type Id.
        /// </summary>
        public static string AdministratorType_AdministratorTypeId {
            get {
                return ResourceManager.GetString("AdministratorType_AdministratorTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string AdministratorType_Type {
            get {
                return ResourceManager.GetString("AdministratorType_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Types.
        /// </summary>
        public static string AdministratorTypePlural {
            get {
                return ResourceManager.GetString("AdministratorTypePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Part.
        /// </summary>
        public static string AutoPart {
            get {
                return ResourceManager.GetString("AutoPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string AutoPart_Article {
            get {
                return ResourceManager.GetString("AutoPart_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Part Car Model.
        /// </summary>
        public static string AutoPart_AutoPartCarModel {
            get {
                return ResourceManager.GetString("AutoPart_AutoPartCarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Part Category.
        /// </summary>
        public static string AutoPart_AutoPartCategory {
            get {
                return ResourceManager.GetString("AutoPart_AutoPartCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Part Id.
        /// </summary>
        public static string AutoPart_AutoPartId {
            get {
                return ResourceManager.GetString("AutoPart_AutoPartId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Part Manufacturer.
        /// </summary>
        public static string AutoPart_AutoPartManufacturer {
            get {
                return ResourceManager.GetString("AutoPart_AutoPartManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string AutoPart_Cost {
            get {
                return ResourceManager.GetString("AutoPart_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Part Code.
        /// </summary>
        public static string AutoPart_ManufacturerPartCode {
            get {
                return ResourceManager.GetString("AutoPart_ManufacturerPartCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Part Car Model.
        /// </summary>
        public static string AutoPartCarModel {
            get {
                return ResourceManager.GetString("AutoPartCarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Part Car Model Id.
        /// </summary>
        public static string AutoPartCarModel_AutoPartCarModelId {
            get {
                return ResourceManager.GetString("AutoPartCarModel_AutoPartCarModelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string AutoPartCarModel_Brand {
            get {
                return ResourceManager.GetString("AutoPartCarModel_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string AutoPartCarModel_Model {
            get {
                return ResourceManager.GetString("AutoPartCarModel_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Part Car Models.
        /// </summary>
        public static string AutoPartCarModelPlural {
            get {
                return ResourceManager.GetString("AutoPartCarModelPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Part Category.
        /// </summary>
        public static string AutoPartCategory {
            get {
                return ResourceManager.GetString("AutoPartCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Part Category Id.
        /// </summary>
        public static string AutoPartCategory_AutoPartCategoryId {
            get {
                return ResourceManager.GetString("AutoPartCategory_AutoPartCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string AutoPartCategory_Category {
            get {
                return ResourceManager.GetString("AutoPartCategory_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Part Categories.
        /// </summary>
        public static string AutoPartCategoryPlural {
            get {
                return ResourceManager.GetString("AutoPartCategoryPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Part Manufacturer.
        /// </summary>
        public static string AutoPartManufacturer {
            get {
                return ResourceManager.GetString("AutoPartManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Part Manufacturer Id.
        /// </summary>
        public static string AutoPartManufacturer_AutoPartManufacturerId {
            get {
                return ResourceManager.GetString("AutoPartManufacturer_AutoPartManufacturerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string AutoPartManufacturer_Manufacturer {
            get {
                return ResourceManager.GetString("AutoPartManufacturer_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Part Manufacturers.
        /// </summary>
        public static string AutoPartManufacturerPlural {
            get {
                return ResourceManager.GetString("AutoPartManufacturerPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Parts.
        /// </summary>
        public static string AutoPartPlural {
            get {
                return ResourceManager.GetString("AutoPartPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeeper.
        /// </summary>
        public static string Bookkeeper {
            get {
                return ResourceManager.GetString("Bookkeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeeper Id.
        /// </summary>
        public static string Bookkeeper_BookkeeperId {
            get {
                return ResourceManager.GetString("Bookkeeper_BookkeeperId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string Bookkeeper_MiddleName {
            get {
                return ResourceManager.GetString("Bookkeeper_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Bookkeeper_Name {
            get {
                return ResourceManager.GetString("Bookkeeper_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Bookkeeper_Surname {
            get {
                return ResourceManager.GetString("Bookkeeper_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeeper Contact.
        /// </summary>
        public static string BookkeeperContact {
            get {
                return ResourceManager.GetString("BookkeeperContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeeper.
        /// </summary>
        public static string BookkeeperContact_Bookkeeper {
            get {
                return ResourceManager.GetString("BookkeeperContact_Bookkeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeeper Contact Id.
        /// </summary>
        public static string BookkeeperContact_BookkeeperContactId {
            get {
                return ResourceManager.GetString("BookkeeperContact_BookkeeperContactId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        public static string BookkeeperContact_ContactType {
            get {
                return ResourceManager.GetString("BookkeeperContact_ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string BookkeeperContact_Value {
            get {
                return ResourceManager.GetString("BookkeeperContact_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeeper Contacts.
        /// </summary>
        public static string BookkeeperContactPlural {
            get {
                return ResourceManager.GetString("BookkeeperContactPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeepers.
        /// </summary>
        public static string BookkeeperPlural {
            get {
                return ResourceManager.GetString("BookkeeperPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeeper Salary.
        /// </summary>
        public static string BookkeeperSalary {
            get {
                return ResourceManager.GetString("BookkeeperSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeeper.
        /// </summary>
        public static string BookkeeperSalary_Bookkeeper {
            get {
                return ResourceManager.GetString("BookkeeperSalary_Bookkeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeeper Salary Id.
        /// </summary>
        public static string BookkeeperSalary_BookkeeperSalaryId {
            get {
                return ResourceManager.GetString("BookkeeperSalary_BookkeeperSalaryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string BookkeeperSalary_IssueDate {
            get {
                return ResourceManager.GetString("BookkeeperSalary_IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string BookkeeperSalary_Salary {
            get {
                return ResourceManager.GetString("BookkeeperSalary_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeeper Salaries.
        /// </summary>
        public static string BookkeeperSalaryPlural {
            get {
                return ResourceManager.GetString("BookkeeperSalaryPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        public static string ContactType {
            get {
                return ResourceManager.GetString("ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type Id.
        /// </summary>
        public static string ContactType_ContactTypeId {
            get {
                return ResourceManager.GetString("ContactType_ContactTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ContactType_Type {
            get {
                return ResourceManager.GetString("ContactType_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Types.
        /// </summary>
        public static string ContactTypePlural {
            get {
                return ResourceManager.GetString("ContactTypePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string Customer_BirthDate {
            get {
                return ResourceManager.GetString("Customer_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Id.
        /// </summary>
        public static string Customer_CustomerId {
            get {
                return ResourceManager.GetString("Customer_CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string Customer_MiddleName {
            get {
                return ResourceManager.GetString("Customer_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Customer_Name {
            get {
                return ResourceManager.GetString("Customer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Customer_Surname {
            get {
                return ResourceManager.GetString("Customer_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Contact.
        /// </summary>
        public static string CustomerContact {
            get {
                return ResourceManager.GetString("CustomerContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        public static string CustomerContact_ContactType {
            get {
                return ResourceManager.GetString("CustomerContact_ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cusomer Contact Id.
        /// </summary>
        public static string CustomerContact_CusomerContactId {
            get {
                return ResourceManager.GetString("CustomerContact_CusomerContactId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string CustomerContact_Customer {
            get {
                return ResourceManager.GetString("CustomerContact_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string CustomerContact_Value {
            get {
                return ResourceManager.GetString("CustomerContact_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Contacts.
        /// </summary>
        public static string CustomerContactPlural {
            get {
                return ResourceManager.GetString("CustomerContactPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string CustomerPlural {
            get {
                return ResourceManager.GetString("CustomerPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Address.
        /// </summary>
        public static string Order_Address {
            get {
                return ResourceManager.GetString("Order_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Address.
        /// </summary>
        public static string Order_Address1 {
            get {
                return ResourceManager.GetString("Order_Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Part.
        /// </summary>
        public static string Order_AutoPart {
            get {
                return ResourceManager.GetString("Order_AutoPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Order_Customer {
            get {
                return ResourceManager.GetString("Order_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Order_Date {
            get {
                return ResourceManager.GetString("Order_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Created Date Time.
        /// </summary>
        public static string Order_OrderCreatedDateTime {
            get {
                return ResourceManager.GetString("Order_OrderCreatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Finished Date Time.
        /// </summary>
        public static string Order_OrderFinishedDateTime {
            get {
                return ResourceManager.GetString("Order_OrderFinishedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id.
        /// </summary>
        public static string Order_OrderId {
            get {
                return ResourceManager.GetString("Order_OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string Order_OrderStatu {
            get {
                return ResourceManager.GetString("Order_OrderStatu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller.
        /// </summary>
        public static string Order_Seller {
            get {
                return ResourceManager.GetString("Order_Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string OrderPlural {
            get {
                return ResourceManager.GetString("OrderPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string OrderStatu {
            get {
                return ResourceManager.GetString("OrderStatu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status Id.
        /// </summary>
        public static string OrderStatu_OrderStatusId {
            get {
                return ResourceManager.GetString("OrderStatu_OrderStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string OrderStatu_Status {
            get {
                return ResourceManager.GetString("OrderStatu_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Statuses.
        /// </summary>
        public static string OrderStatuPlural {
            get {
                return ResourceManager.GetString("OrderStatuPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller.
        /// </summary>
        public static string Seller {
            get {
                return ResourceManager.GetString("Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string Seller_MiddleName {
            get {
                return ResourceManager.GetString("Seller_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Seller_Name {
            get {
                return ResourceManager.GetString("Seller_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Id.
        /// </summary>
        public static string Seller_SellerId {
            get {
                return ResourceManager.GetString("Seller_SellerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Seller_Surname {
            get {
                return ResourceManager.GetString("Seller_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Contact.
        /// </summary>
        public static string SellerContact {
            get {
                return ResourceManager.GetString("SellerContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        public static string SellerContact_ContactType {
            get {
                return ResourceManager.GetString("SellerContact_ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller.
        /// </summary>
        public static string SellerContact_Seller {
            get {
                return ResourceManager.GetString("SellerContact_Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Contact Id.
        /// </summary>
        public static string SellerContact_SellerContactId {
            get {
                return ResourceManager.GetString("SellerContact_SellerContactId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string SellerContact_Value {
            get {
                return ResourceManager.GetString("SellerContact_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Contacts.
        /// </summary>
        public static string SellerContactPlural {
            get {
                return ResourceManager.GetString("SellerContactPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sellers.
        /// </summary>
        public static string SellerPlural {
            get {
                return ResourceManager.GetString("SellerPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Salary.
        /// </summary>
        public static string SellerSalary {
            get {
                return ResourceManager.GetString("SellerSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string SellerSalary_IssueDate {
            get {
                return ResourceManager.GetString("SellerSalary_IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string SellerSalary_Salary {
            get {
                return ResourceManager.GetString("SellerSalary_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller.
        /// </summary>
        public static string SellerSalary_Seller {
            get {
                return ResourceManager.GetString("SellerSalary_Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Salary Id.
        /// </summary>
        public static string SellerSalary_SellerSalaryId {
            get {
                return ResourceManager.GetString("SellerSalary_SellerSalaryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Salaries.
        /// </summary>
        public static string SellerSalaryPlural {
            get {
                return ResourceManager.GetString("SellerSalaryPlural", resourceCulture);
            }
        }
    }
}
