//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoPart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutoPart()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int AutoPartId { get; set; }
        public int AutoPartCategoryId { get; set; }
        public int AutoPartManufacturerId { get; set; }
        public int AutoPartCarModelId { get; set; }
        public string Article { get; set; }
        public string ManufacturerPartCode { get; set; }
        public decimal Cost { get; set; }
    
        public virtual AutoPartCarModel AutoPartCarModel { get; set; }
        public virtual AutoPartCategory AutoPartCategory { get; set; }
        public virtual AutoPartManufacturer AutoPartManufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
