//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public int SellerId { get; set; }
        public int CustomerId { get; set; }
        public int AutoPartId { get; set; }
        public int OrderStatusId { get; set; }
        public Nullable<System.DateTime> OrderCreatedDateTime { get; set; }
        public Nullable<System.DateTime> OrderFinishedDateTime { get; set; }
        public int From_AdressId { get; set; }
        public int To_AdressId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual AutoPart AutoPart { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
