//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerSalary
    {
        public int SellerSalaryId { get; set; }
        public decimal Salary { get; set; }
        public System.DateTime IssueDate { get; set; }
        public int SellerId { get; set; }
    
        public virtual Seller Seller { get; set; }
    }
}
